### ISSUE TITLE
Registry?

### ISSUE THREAD

**Issue by tpoisot** [EcoJulia/EcoJulia.org#2]
@mkborregaard what do you think of turning `EcoJulia` in a registry for 1.0?

**Comment by mkborregaard** [comment]
I'm not sure what you mean, sorry?

**Comment by tpoisot** [comment]
Nevermind -- there is currently the *Uncurated* registry with (possible) plans to support org-level registries, but that's apparently not for the near future.

**Comment by mkborregaard** [comment]
Oh I see - yes everything is in uncurated now but I definitely think we should work towards getting into the walled garden. Let me reopen the issue as a reminder.

**Comment by tpoisot** [comment]
Good call. The way I understand it, it would let people work from their own repos /orgs, and the registry would aggregate all these packages. I think this makes sense.
