### ISSUE TITLE
Juliacon

### ISSUE THREAD

**Issue by tpoisot** [EcoJulia/EcoJulia.org#3]
Do we want to submit something for Juliacon? It's not far from Montreal so I'll go, and I think it's worth being present.

**Comment by mkborregaard** [comment]
Yes absolutely, that's a great idea! I don't think I'll make it to JuliaCon (though I might be in Montreal in June). Did you see the comments I made on GBIF? I've got a branch I've been using on 1.1 (`mkb/dev`=. I'm happy to help with getting the things done that needs for the 1.0 compat to be merged.

**Comment by pdimens** [comment]
Archiving this thread
