### ISSUE TITLE
New publication using EcologicalNetworks

### ISSUE THREAD

**Issue by tpoisot** [EcoJulia/EcoJulia.org#8]
Strydom, T., Dalla Riva, G. V., & Poisot, T. (2020, November 2). SVD entropy reveals the high complexity of ecological networks. https://doi.org/10.32942/osf.io/q9v85

Not sure where to add them, I'm ignorant as to how Franklin works!

**Comment by pdimens** [comment]
All the stuff would go to the `publications.md` file on the `dev` branch.

Added via https://github.com/EcoJulia/EcoJulia.org/commit/206629af50f97238095e767f14e06444ad8bb307
